# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
export DISABLE_MAGIC_FUNCTIONS="true"

zstyle ':omz:update' mode disabled

source $ZSH/oh-my-zsh.sh

# Options
setopt no_nomatch
setopt nullglob
setopt inc_append_history
setopt share_history
setopt PROMPT_SUBST

bindkey -e

# Autoloads
autoload -U colors && colors

# Path
export PATH=$HOME/.local/bin:$PATH
export PATH=/var/lib/flatpak/exports/bin:$PATH
export PATH=$HOME/.local/share/flatpak/exports/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/go/bin:$PATH

export FPATH=$HOME/.local/share/kde-builder/data/completions/zsh/:$FPATH

# man pages
export MANPATH="/usr/local/man:$MANPATH"

# Default editor
export EDITOR=nvim

export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.zsh_history

# Alias
alias ls='ls --group-directories-first --color=tty'
alias mkdir='mkdir -p'
alias ggrep='git grep'
alias rgrep='grep -R'
alias tree='tree --dirsfirst --gitignore'
alias expand_alias='echo '
alias color='unbuffer '
alias bell='printf "\a"'
alias nvimdiff='nvim -d'

# Functions
# open command
function open () {
    xdg-open $@ &> /dev/null
}

# app command
function app () {
    ( $@ &> /dev/null & ) ;
}

# cmake compiler macros
function cmake_clang() {
  export CXX=/usr/bin/clang++
  export CC=/usr/bin/clang
}

function cmake_gnu() {
  export CXX=/usr/bin/g++
  export CC=/usr/bin/gcc
}

function venv_name() {
  [ $VIRTUAL_ENV ] && echo "%{$fg[white]%}🐍"$(basename $VIRTUAL_ENV)"$reset_color "
}

function container_name() {
  [ $CONTAINER_ID ] && echo "%{$fg[cyan]%}📦"$CONTAINER_ID"$reset_color "
}

function git_branch_name() {
  local branch=$(git symbolic-ref --short HEAD 2> /dev/null)
  [ $branch ] && echo "%{$fg[yellow]%}💡"$branch"$reset_color "
}

# Theme
VIRTUAL_ENV_DISABLE_PROMPT=1

local path_view="%B%{$fg[blue]%}%~$reset_color "
local return_code="%(?..%B$fg[red]%?$reset_color) "

if [ $(whoami) == root ]; then
  local user_name="%B%{$fg[red]%}%n@%m%{$reset_color%} "
  local symbol="# "
else
  local user_name="%B%{$fg[green]%}%n@%m%{$reset_color%} "
  local symbol="$ "
fi

PROMPT='${user_name}$(container_name)$(venv_name)$(git_branch_name)${path_view}${return_code}
${symbol}'

# fzf
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix --hidden --exclude '.git'"

# Plugins
local syntax=$(find /usr/share/zsh* -name "zsh-syntax-highlighting.zsh")
if [ $syntax ] && [ -e $syntax ]; then
  source $syntax
fi

# change default compiler to clang
cmake_clang

function load_tmux () {
  local tmux_sessions=$(tmux ls 2> /dev/null)

  if [ -z $TMUX ] && [ -z $CONTAINER_ID ]; then
    if [ $tmux_sessions ]; then
      local first=$(echo $tmux_sessions | head -n 1 | cut -d ':' -f 1)
      tmux attach-session -t $first \; new-window -c "$PWD"
    else
      tmux new-session -c "$PWD"
    fi
    exit
  fi
}
