# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
export DISABLE_MAGIC_FUNCTIONS="true"

zstyle ':omz:update' mode disabled

source $ZSH/oh-my-zsh.sh

# Options
setopt no_nomatch
setopt nullglob
setopt inc_append_history
setopt share_history
setopt PROMPT_SUBST

bindkey -e

# Autoloads
autoload -U colors && colors

# Path
export PATH=$HOME/.local/bin:$PATH
export PATH=/var/lib/flatpak/exports/bin:$PATH
export PATH=$HOME/.local/share/flatpak/exports/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/go/bin:$PATH

export FPATH=$HOME/.local/share/kde-builder/data/completions/zsh/:$FPATH

# man pages
export MANPATH="/usr/local/man:$MANPATH"

# Default editor
export EDITOR=nvim

export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.zsh_history

# Alias
alias ls='ls --group-directories-first --color=tty'

alias mkdir='mkdir -p'

alias ggrep='git grep'
alias rgrep='grep -R'

alias tree='tree --dirsfirst --gitignore'

alias expand_alias='echo '
alias color='unbuffer '
alias bell='printf "\a"'

alias fvim='nvim $(fzf)'
alias nvimdiff='nvim -d'
alias emacs='emacs -nw'

alias mobile='QT_QUICK_CONTROLS_MOBILE=true '

alias dev='distrobox enter dev'
alias kali='distrobox enter kali'
alias study='distrobox enter study'

alias ga='git add'
alias gap='git add -p'

alias gb='git branch'
alias gba='git branch --all'

alias gs='git status -u'

alias gc='git commit'
alias gcm='git commit -m'

alias gp='git push'
alias gpd='git push --dry-run'

alias gl='git pull'

alias gf='git fetch'

alias gr='git remote -v'
alias gra='git remote add'
alias grr='git remote rename'

alias gd='git diff'
alias gds='git diff --staged'

alias gg='git log --oneline --graph --decorate=full --all'

# Functions

# open command
function open () {
    xdg-open $@ &> /dev/null
}

# app command
function app () {
    ( $@ &> /dev/null & ) ;
}

# cmake compiler macros
function cmake_clang() {
  export CXX=/usr/bin/clang++
  export CC=/usr/bin/clang
}

function cmake_gnu() {
  export CXX=/usr/bin/g++
  export CC=/usr/bin/gcc
}

function mkcd() {
  mkdir $@
  cd $@
}

function path() {
  echo "${PWD/#$HOME/~}"
}

# Theme
VIRTUAL_ENV_DISABLE_PROMPT=1

function _p_venv() {
  [ $VIRTUAL_ENV ] && echo "$fg_bold[white]🐍$(basename $VIRTUAL_ENV)$reset_color "
}

function _p_box() {
  [ $CONTAINER_ID ] && echo "$fg_bold[cyan]📦$CONTAINER_ID$reset_color "
}

function _p_git() {
  local branch=$(git symbolic-ref --short HEAD 2> /dev/null)
  [ $branch ] && echo "$fg_bold[yellow]💡$branch$reset_color "
}

function _p_dir() {
  echo "$fg_bold[blue]$(basename $(path))$reset_color"
}

function _p_path() {
  echo "$fg_bold[blue]$(path)$reset_color "
}

function _p_ret() {
  echo "%(?..$fg_bold[red]%?$reset_color)"
}

function _p_sym() {
  if [ $(whoami) == root ]; then
    echo "$bold_color#$reset_color"
  else
    echo "$bold_color\$$reset_color"
  fi
}

function _p_user_host() {
  _p_user
  printf "@"
  printf "$fg_bold[magenta]$HOST$reset_color "
}

function _p_user() {
  if [ $(whoami) == root ]; then
    printf "$fg_bold[cyan]$SUDO_USER$reset_color"
    printf " as "
    printf "$fg_bold[red]$USER$reset_color"
  else
    printf "$fg_bold[cyan]$USER$reset_color"
  fi
}

function _p_prompt() {
  echo $(_p_sym)
}

function _p_line_1() {
  echo $(_p_user_host) $(_p_box) $(_p_venv) $(_p_git) $(_p_dir) $(_p_ret)
}

PROMPT='%1{$(_p_line_1)%}
%1{$(_p_prompt)%} '

# fzf
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix --hidden --exclude '.git'"

# Plugins
local syntax=$(find /usr/share/zsh* -name "zsh-syntax-highlighting.zsh")
if [ $syntax ] && [ -e $syntax ]; then
  source $syntax
fi

# change default compiler to clang
cmake_clang

function load_tmux () {
  local tmux_sessions=$(tmux ls 2> /dev/null)

  if [ -z $TMUX ] && [ -z $CONTAINER_ID ]; then
    if [ $tmux_sessions ]; then
      local first=$(echo $tmux_sessions | head -n 1 | cut -d ':' -f 1)
      tmux attach-session -t $first \; new-window -c "$PWD"
    else
      tmux new-session -c "$PWD"
    fi
    exit
  fi
}

eval "$(zoxide init zsh)"
