export ZSH="$HOME/.oh-my-zsh"

# Options
setopt no_nomatch
setopt nullglob

# Path
export PATH=$HOME/.local/bin:$PATH
export PATH=/var/lib/flatpak/exports/bin:$PATH
export PATH=$HOME/.local/share/flatpak/exports/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH

export FPATH=$HOME/.local/share/kde-builder/data/completions/zsh/:$FPATH

# Theme
ZSH_THEME="ktheme"

# tmux
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_CONFIG=~/.config/tmux/tmux.conf

# fzf
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix --hidden --exclude '.git'"

# Disable automatic updates
zstyle ':omz:update' mode disabled

# Plugins
plugins=(tmux virtualenv zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# man pages
export MANPATH="/usr/local/man:$MANPATH"

# Default editor
export EDITOR=nvim

# Alias
alias ls='ls --group-directories-first --color=tty'
alias mkdir='mkdir -p'
alias ggrep='git grep'
alias rgrep='grep -R'
alias tree='tree --dirsfirst --gitignore'
alias expand_alias='echo '
alias color='unbuffer '
alias bell='printf "\a"'
alias nvimdiff='nvim -d'

# open command
function open () {
    xdg-open $@ &> /dev/null
}

# app command
function app () {
    ( $@ &> /dev/null & ) ;
}

# cmake compiler macros
function cmake_clang() {
  export CXX=/usr/bin/clang++
  export CC=/usr/bin/clang
}

function cmake_gnu() {
  export CXX=/usr/bin/g++
  export CC=/usr/bin/gcc
}

# change default compiler to clang
cmake_clang

# Autocompletions
compdef -d git
